spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb_sec?currentSchema=public
    username: postgres
    password: passer
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true

server:
  port: 8083
# server:
#   port: 15101
#   ssl:
#     key-store: classpath:keystore/keystore.p12
#     key-store-password: THBS4life
#     key-store-type: PKCS12
#     key-alias: aerd
#     enabled: true

#31:49
management:
  endpoints:
    web:
      exposure.include: ['configprops', 'env', 'health', 'info', 'metrics', 'logfile', 'loggers', 'prometheus', 'threaddump']

springdoc:
  api-docs.path: /api-docs 
  swagger-ui.path: /swagger-ui-custom.html
